vich_uploader:
    db_driver: orm

    mappings:
        image_magasins:
           uri_prefix: /images/magasins
           upload_destination: '%kernel.project_dir%/public/images/magasins'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
           
           inject_on_load: false
           delete_on_update: true
           delete_on_remove: true
        
        image_articles:
           uri_prefix: /images/articles
           upload_destination: '%kernel.project_dir%/public/images/articles'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
           
           inject_on_load: false
           delete_on_update: true
           delete_on_remove: true